# Generated by Django 4.1.1 on 2025-12-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('ip_address', 'user_agent', 'date')},
            },
        ),
    ]
