# Generated by Django 3.2 on 2022-05-15 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20220510_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='first_paragraph',
            field=models.TextField(help_text='First paragrap of article', null=True),
        ),
        migrations.AlterField(
            model_name='blogdetailpage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
