# Generated by Django 3.2 on 2022-05-15 20:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0003_auto_20220515_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True, null=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Blog Author',
                'verbose_name_plural': 'Blog Authors',
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Blog Article Category',
                'verbose_name_plural': 'Blog Article Categories',
            },
        ),
        migrations.RenameField(
            model_name='blogdetailpage',
            old_name='first_paragraph',
            new_name='content_first_paragraph',
        ),
        migrations.RemoveField(
            model_name='blogdetailpage',
            name='author',
        ),
        migrations.AddField(
            model_name='blogdetailpage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 5, 15, 20, 45, 29, 980323, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BlogAuthorsOrderable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.blogauthor')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_authors', to='home.blogdetailpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blogdetailpage',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category of blog article', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.blogcategory'),
        ),
    ]
